### ISSUE TITLE
Roadmap of migrating kaizen -> into new caesar theme generator

### ISSUE THREAD

**Issue by koskinpark** [skilld-labs/ui-patterns-kaizen#8]
### What's required:
1. Naming of the new theme generator. (`caesar` or some other)
2. Ability to generate theme by different ways:
2.1. Generate theme using php & drupal command `generate-theme` https://www.drupal.org/node/3206389
2.2. Generate theme using `npx`
2.3. Generate theme using docker container (probably `npx`, but called from docker)
2.4. Should we release a new contrib starterkit theme on d.org -> store theme generator on git.drupalcode.org ? or skilld's github ?
3. Replacement of webpack to vite
4. Storybook v7
5. Re-think the naming of sub-folders in theme
6. Rework component generator (`kaizen-cg`) to follow new concept of doing components.
6.1. Review component-name.js file inners for component generator
6.2. Review component-name.yml file inners for component generator
6.3. Review component-name.twig file inners for component generator
6.3. Review component-name.stories.js file inners for component generator
7. Define a list of all basic components (texts, form element's components, page layout maybe, something else?)
8. Code all basic components, defined in (7)
9. Write detailed README of how to use theme generator and component generator
10. Define & code a list of drupal's breakpoints
11. Add svg-sprite generator
12. Add favicon generator
13. Add image-optimizer scripts, kinda https://squoosh.app/
14. Update prettier, stylelint, eslint, browserlist configs to follow latest drupal core
15. Review themename.theme file. What's required to be inside by default?
16. Convert all images, attached from css -> to base64 format
17. In which folder(s) to build assets
18. Defined where npm libraries should live / how should be used & apply solution
19. Define coding-standards of writing css variables
20. How to define & attach drupal libraries for patterns / no patterns.

Post-release features:
1. Ability to simply share components between projects
2. ?

**Comment by andypost** [comment]
Why new name? The `kaizen-tg` already doing some of tasks, `caezar` is good for base theme but maybe we can ressurect `zen`?

**Comment by iberdinsky-skilld** [comment]
### Step by step roadmap
#### Prepare
- [x] Replacement of webpack by vite
- [x] Storybook v7
- [x] Add svg-sprite generator
- [x] Add favicon generator
- [x] Update prettier, stylelint, eslint, browserlist configs to follow latest drupal core
- [x] Review postcss config & kick/add plugins which we still need/no need
- [x] Add support of yml in storybook with UI Patterns based contents
- [x] Add support of most of drupal's regular twig functions in storybook
- [x] Rework kaizen-breakpoints package to something more simple -> to be able to use drupal's breakpoints in css and js
- [x] Provide concept of creation all image style configs and responsive image groups in storybook / re-use those configs in storybook to build images
- [ ] Generate dummy page with components based on new approach. (most simplest styles/no pixel perfect/no hovers etc). 
- [ ] Adapt components from SB to Drupal using different adaptations technics. 

#### Decisions
- [ ] Define & code a list of drupal's breakpoints
- [ ] Review themename.theme file. What's required to be inside by default?
- [ ] In which folder(s) to build assets
- [ ] Define where npm libraries should live / how should be used & apply solution
- [ ] How to define & attach drupal libraries for patterns / no patterns.
- [ ] Keeping compiled assets in git, but withthout external libs sources
- [ ] Define what CI requires from our theme generator & update in SDC
- [ ] Review of global scripts attached
- [ ] [Re-think the naming of sub-folders in theme](https://github.com/skilld-labs/ui-patterns-kaizen/issues/10)
- - [ ] Review component-name.js file inners for component generator
- - [ ] Review component-name.yml file inners for component generator
- - [ ] Review component-name.twig file inners for component generator
- - [ ] Review component-name.stories.js file inners for component generator
- [ ] [Define a list of all basic components (texts, form element's components, page layout maybe, something else?)](https://github.com/skilld-labs/ui-patterns-kaizen/issues/9)
- [ ] Code all basic components, defined in (7)
- [ ] Naming of the new theme generator. (`caesar` or some other)


#### Coding

- [ ] Rework component generator (`kaizen-cg`) to follow new concept of doing components.
- [ ] Ability to generate theme by different ways:
- - [ ] Generate theme using php & drupal command `generate-theme` https://www.drupal.org/node/3206389
- - [ ] Generate theme using `npx`
- - [ ] Generate theme using docker container (probably `npx`, but called from docker)
- - [ ] Should we release a new contrib starterkit theme on d.org -> store theme generator on git.drupalcode.org ? or skilld's github ?
- [ ] Write detailed README of how to use theme generator and component generator
- [ ] Build test page to test easily a whole caesar's functionalities



### Potential features which can be included in alpha release
- [ ] Define coding-standards of writing css variables
- [ ] Add image-optimizer scripts, kinda https://squoosh.app/
- [ ] Convert all images, attached from css -> to base64 format
?

### Post-release features:
- [ ] Ability to simply share components between projects
